// <auto-generated />
using System;
using EcommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120012125_AddTiendaContactAndEstado")]
    partial class AddTiendaContactAndEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApi.Models.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TiendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TiendaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dispositivos electrónicos",
                            Nombre = "Electrónica",
                            TiendaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Prendas de vestir",
                            Nombre = "Ropa",
                            TiendaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Artículos para el hogar",
                            Nombre = "Hogar",
                            TiendaId = 1
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDespacho")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSeguimiento")
                        .HasColumnType("text");

                    b.Property<string>("ServicioEnvio")
                        .HasColumnType("text");

                    b.Property<int>("TiendaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TransaccionId")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TiendaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("EcommerceApi.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.PlanSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxProductos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanesSuscripcion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Ideal para emprendedores que están comenzando",
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 23, 687, DateTimeKind.Utc).AddTicks(9009),
                            MaxProductos = 20,
                            Nombre = "Plan Básico",
                            PrecioMensual = 2999.99m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Perfecto para negocios en crecimiento",
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 23, 687, DateTimeKind.Utc).AddTicks(9674),
                            MaxProductos = 30,
                            Nombre = "Plan Estándar",
                            PrecioMensual = 4999.99m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Para negocios establecidos con catálogo mediano",
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 23, 687, DateTimeKind.Utc).AddTicks(9678),
                            MaxProductos = 50,
                            Nombre = "Plan Profesional",
                            PrecioMensual = 7999.99m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Sin límites para grandes emprendimientos",
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 23, 687, DateTimeKind.Utc).AddTicks(9681),
                            MaxProductos = 100,
                            Nombre = "Plan Premium",
                            PrecioMensual = 12999.99m
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<int>("TiendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("EcommerceApi.Models.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiEnvioCredenciales")
                        .HasColumnType("text");

                    b.Property<string>("ApiEnvioProveedor")
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EnvioHabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoTienda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSuscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoSuscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkInstagram")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxProductos")
                        .HasColumnType("integer");

                    b.Property<string>("MercadoPagoAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoPublicKey")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanSuscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoWhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanSuscripcionId");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Tiendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EnvioHabilitado = false,
                            EstadoTienda = "Borrador",
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 23, 691, DateTimeKind.Utc).AddTicks(1482),
                            MaxProductos = 100,
                            Nombre = "Tienda Demo",
                            PlanSuscripcionId = 4,
                            Subdominio = "demo"
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TiendaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ecommerce.com",
                            EmailVerificado = false,
                            FechaCreacion = new DateTime(2026, 1, 20, 1, 21, 24, 135, DateTimeKind.Utc).AddTicks(3632),
                            Nombre = "Super Administrador",
                            PasswordHash = "$2a$11$qatfjdSykrkFWeyG4nRLAOibIdUfz4vdYFsQizqY0XnIE7cYr.IWW",
                            Rol = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.CarritoItem", b =>
                {
                    b.HasOne("EcommerceApi.Models.Producto", "Producto")
                        .WithMany("CarritoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Usuario", null)
                        .WithMany("CarritoItems")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcommerceApi.Models.Categoria", b =>
                {
                    b.HasOne("EcommerceApi.Models.Tienda", "Tienda")
                        .WithMany("Categorias")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("EcommerceApi.Models.Pedido", b =>
                {
                    b.HasOne("EcommerceApi.Models.Tienda", "Tienda")
                        .WithMany("Pedidos")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tienda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcommerceApi.Models.PedidoItem", b =>
                {
                    b.HasOne("EcommerceApi.Models.Pedido", "Pedido")
                        .WithMany("PedidoItems")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Producto", "Producto")
                        .WithMany("PedidoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EcommerceApi.Models.Producto", b =>
                {
                    b.HasOne("EcommerceApi.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Tienda", "Tienda")
                        .WithMany("Productos")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("EcommerceApi.Models.Tienda", b =>
                {
                    b.HasOne("EcommerceApi.Models.PlanSuscripcion", "PlanSuscripcion")
                        .WithMany("Tiendas")
                        .HasForeignKey("PlanSuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlanSuscripcion");
                });

            modelBuilder.Entity("EcommerceApi.Models.Usuario", b =>
                {
                    b.HasOne("EcommerceApi.Models.Tienda", "Tienda")
                        .WithMany("Usuarios")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("EcommerceApi.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("EcommerceApi.Models.Pedido", b =>
                {
                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.PlanSuscripcion", b =>
                {
                    b.Navigation("Tiendas");
                });

            modelBuilder.Entity("EcommerceApi.Models.Producto", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.Tienda", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Pedidos");

                    b.Navigation("Productos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EcommerceApi.Models.Usuario", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
